FROM node:21-alpine3.17

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
RUN ls -a
RUN npm install && npm install -g ts-node-dev

EXPOSE 4003

CMD ["npm", "run", "dev"]